### ISSUE TITLE
As an admin, I would like to download a CSV of volunteer assignments data

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/community-curation#10]

**Comment by yugen** [comment]
@courtneythaxton You can take a look at the first pass of the assignments report download by visiting [http://community-curation.sirsdemo.unc.edu/volunteers](http://community-curation.sirsdemo.unc.edu/volunteers) and clicking on the 'assignments report' button in the upper right corner.

Please focus on the format of the download as the import is not fully correct and the data you see may not reflect what is in the google sheet.

Also, I'm not yet doing any filtering of the report based on filters in the UI.  Because filtering can be done w/in excel, I figured we might want to punt on that enhancement until we're done with all of the work required to go live.  If you feel like that feature is necessary for launch we can certainly add an issue and add it to the Version 1 milestone.

**Comment by yugen** [comment]
@courtneythaxton I've updated the date formatting for training and attestation dates.  Also, imports are now updated volunteer status based on what I know so you should be seeing unresponsive/declined, active, etc. in the status column in addition to trained and applied.

**Comment by courtneythaxton** [comment]
Hi @yugen TJ, this looks really nice! At this point, any one can sort on curation activity, date trained, assigned expert panel, and the number of curation activities, so this hits all the points for metric reporting.

The curation activity specific tabs are also so nice!

For the survey dates, I do have a question specifically for the imported data (which may require a separate ticket but I thought I would ask), would we be able to update the date with the one from the initial survey logs from the google doc? We do reporting based on the number of people that have taken the survey in a set time frame. 

Thanks @courtneythaxton

**Comment by yugen** [comment]
@courtneythaxton, I'll look into the survey date issue.  My intention was to provide the date that matches the google sheet.  It's either an oversight in the import or a bug in the report generation.  I'll look into that and get back to you.

**Comment by yugen** [comment]
@courtneythaxton Looks like I forgot to set the dates on the Survey data based on the google sheet.  That's updated and you should see those dates on the exports now.

**Comment by courtneythaxton** [comment]
@yugen The assignment report looks great. Thank you for updating the survey dates.

**Comment by yugen** [comment]
Closing issue.  If we want to add filtering functionality we can create a new GH issue.
