### ISSUE TITLE
Admin function to delete working groups and curation groups

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/community-curation#101]
**Is your feature request related to a problem? Please describe.**
At this time as an admin, I do not have the capability to remove a working group or curation group from the list. Some of these groups either need updating, or there are duplicates. Would we just list these individuals to you TJ, as the developer to remove? I figure this should be an infrequent occurrence. Or would it be to hard to allow myself and Brooke at least to delete these groups?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yugen** [comment]
@courtneythaxton 

There are a couple of questions we'll need to answer before we can implement this:

1. What happens if a WG you're trying to delete has EPs associated with it?
2. What happens if a volunteer has been assigned to an EP you are trying to delete?

**Comment by courtneythaxton** [comment]
Thanks @yugen You do bring up good questions for this. 

I suppose for now I can see if anyone is assigned to these EPs, and that may help. For instance there is a "Retina" GCEP and a "Retina GCEP" curation group. These would both represent the same entity and be duplicative.

We also have a few EPs that are orphans in ClinGen, meaning they have no overarching CDWG (working group), these include the syndromic GCEP, the Malignant hyperthermia VCEP, and the Parkinson's GCEP. I generally put these orphan groups under the Gene Curation Working Group, in the GeneTracker for gene affiliated groups. For variant, I suppose it could be the Genomic Variant WG. But this does bring up a good question on what to do when we have EPs without a parent WG.

**Comment by yugen** [comment]
If there's no one assigned to the groups I can delete them for you manually.  To add a feature to the admin UI we'll need to choose a strategy for dealing with the cases in which there are volunteers/EPs associated with the item being deleted.

Regarding "orphan" EPs, we can change the requirements on the EPs to allow them to not be related to a working group.  I think that's probably the right thing to do if there are, in fact, EPs that are not associated with a CDWG.  

Just let me know how you'd like to proceed and we can get this prioritized and in the queue.

**Comment by courtneythaxton** [comment]
I think for the current duplicates, it would be good for us to review and have you remove them.

For the orphan EPs, I do think it would be good to allow them to be unrelated to a working group to start. We will likely have more as the new U24s EP groups get funded, as there may be EPs that need a CDWG built around them. I would want to make sure that e still leave the ability to associate a working group in the future to those EPs, if possible.

**Comment by yugen** [comment]
Sounds good.
