### ISSUE TITLE
As an admin, I would like to manage all aspects of volunteer assignments in one place

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/community-curation#11]
* Consolidate assignment status, training, attestation actions into a single interface instead of the two separate interfaces we currently have.

**Comment by yugen** [comment]
@courtneythaxton @lizzkearns You can now manage assignment statuses in the same pop-up where you make assignments.  

To test:
1. Go to a volunteer's detail page (ex: https://community-curation.sirsdemo.unc.edu/volunteers/16)
2. Click the 'Manage Assignments' button
3. Next to each assignment (Curation Activity and Expert Panel (or Gene)) you'll see a badge with the current status and pencil icon. 
4. Hover over the badge and a widget will display to the right with a select list of statuses, set to the current status.
5.  Select a new status and the widget will close and the status will get updated.

Please also let me know if you think the user interface is clear/intuitive enough.

Thanks,
TJ

**Comment by courtneythaxton** [comment]
Hi @yugen 

I tested out this new function. 

This looks nice and is intuitive. 

For the widgets on the "Curation Activities side" they look a little fuzzy (see images)
![Screen Shot 2020-03-29 at 12 02 29 AM](https://user-images.githubusercontent.com/32530005/77840017-ab17af80-7150-11ea-8b97-632fcc72dade.png)

It did take a moment to update and at first I had to refresh. I set the Gene to "active" from "Training", and it now shows the new status. 

For Variant I changed from "trained" to "retired." It updated to retired and did a strike through on the word "variant."

One interesting part is that I added a VCEP expert panel even after I made the individual "Retired." And it still shows as assigned.  

Are the activity assignment and Expert panel assignment independent? 

I think it is fine if they are, I would just want to make sure that I note this in the SOP for admins.

**Comment by yugen** [comment]
@courtneythaxton 
- I'm not sure what you mean about fuzzy.  Can you tell me more?
- Updates should be happening without you having to refresh the page.
- I overlooked preventing assignment to EPs/Genes when the CA assignment was retired.  I'll go back and add that back in.

**Comment by courtneythaxton** [comment]
Hi @yugen 

1. The image is blurry, or fuzzy looking. Meaning even with my glasses on it looks blurry :)
2. I do think the updates may have happened while on the page, but I could have been impatient!
3. Thanks for the edits!
