### ISSUE TITLE
Adminy stuff for CDDB:

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/community-curation#119]
* Delete duplicate user (see email)
* give admins permission to 'see clingen member info'

**Comment by yugen** [comment]
@courtneythaxton Both of these items are done.

- Marco Leung's data has been consolidated to user id 78 and 359 has been deleted.
- You can set the display order of Campaigns from their admin screen.  To do so click the 'Reorder Campaigns' button at the top of the admin screen.  You'll be taken to a screen where you can drag and drop them in the order you want to the be displayed.

**Comment by courtneythaxton** [comment]
Thanks!


Courtney

From: TJ Ward ***@***.***>
Reply-To: clingen-data-model/community-curation ***@***.***>
Date: Monday, April 12, 2021 at 3:06 PM
To: clingen-data-model/community-curation ***@***.***>
Cc: Courtney Thaxton ***@***.***>, Mention ***@***.***>
Subject: Re: [clingen-data-model/community-curation] Adminy stuff for CDDB: (#119)


@courtneythaxton<https://github.com/courtneythaxton> Both of these items are done.

  *   Marco Leung's data has been consolidated to user id 78 and 359 has been deleted.
  *   You can set the display order of Campaigns from their admin screen. To do so click the 'Reorder Campaigns' button at the top of the admin screen. You'll be taken to a screen where you can drag and drop them in the order you want to the be displayed.
