### ISSUE TITLE
Build failure: composer.json refers to non-accessible yugen/laravel-db-mail-log

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/community-curation#145]
**Describe the bug**
Unable to build images because of reference to non-accessible (or non-existant?) repo

**To Reproduce**
1. Obtain clean checkout
2. Run `docker-compose up --build`

**Expected behavior**
Docker containers should be built and start running

**Actual behavior**
Build fails during `composer install` with:
```
Failed to download yugen/laravel-db-mail-log from dist: The "https://api.github.com/repos/yugen/laravel-db-mail-log/zipball/6f9e3c32ad413a6e8de9bdf55f824b564c53187c" file could not be downloaded (HTTP/2 404 ):
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#download-a-repository-archive"}
    Now trying to download from source
```

and then later:
```
  [RuntimeException]                                        
  git was not found in your PATH, skipping source download 
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser N/A
 - Docker version 20.10.12, build 20.10.12-0ubuntu4

**Additional context**
It looks like even if git were in the image, it would not work because that repo either no longer exists or is not publicly available. Is this replaceable by another dependency (e.g., was it just patching something fixed upstream)?

**Comment by yugen** [comment]
@bpow  Thanks for the detailed bug report.  I've pulled the dependency directly into this repo since it was owned by me and only used in this project.

I've also updated the readme to include accurate installation instructions.
