### ISSUE TITLE
Ask Baseline volunteers for Hypothes.is id if not recorded

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/community-curation#15]
When a baseline volunteer lands of the volunteer detail screen the system should ask them for their hypothes.is id if they have not yet entered it.

**Comment by courtneythaxton** [comment]
HI @yugen I looked at a baseline volunteer and saw the ability to add a hypothesized.is user ID on the basic information tab for an individual.

On the Baseline Attention, we do ask if the user has created a hypothes,is user account. Would we be able to ask them to enter the name in the attestation, and then have the ID auto populate in the demographics section?

I think it would be good for us to "require" in some way a Baseline individual to have provided this user account ID before they can be assigned a gene.

**Comment by yugen** [comment]
@courtneythaxton Totally possible, but I'm going to add it as a separate issue as it's a change to an attestation, and was not specified as criteria for this issue.  I find it's helpful for managing work to avoid adding scope to issues once they've been started so that we have a record of what is actually done.  Otherwise, what starts out as a small, well defined issue can baloon into something huge and all encompasing.

**Comment by courtneythaxton** [comment]
okay @yugen thank you for creating a new ticket. I will do my bet to remember to do so, but if I forget thank you for the reminders.
