### ISSUE TITLE
As a volunteer, I would like to complete the 6 month follow-up survey for a curation activity/expert panel assignment

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/community-curation#17]
- [x] - volunteer should be able to complete a 6-month survey
- [x] - Voluneer, Admin, and Programmer should be able to review 6-month survey data on volunteer screen
- [x] - System should send volunteer notifications about 6-month survey

**Comment by yugen** [comment]
@courtneythaxton or @lizzkearns Is there an existing 6-month volunteer followup survey or will it be the same as the 3-month?  If they are different please direct me to the latest 6-month Apologies if we've already discussed this and I've forgotten.

**Comment by lizzkearns** [comment]
@yugen There is a separate 6-month survey, here is the link: https://docs.google.com/forms/d/e/1FAIpQLSd07X06VvE7_IxMPQwu400bRqIsMXrd3akiEDoCj74wLHQM_A/viewform

**Comment by yugen** [comment]
Thanks, @lizzkearns!

**Comment by yugen** [comment]
@courtneythaxton Is the volunteer 6-month followup assigned per-expert-panel assignment or per-volunteer?

**Comment by courtneythaxton** [comment]
@yugen, good question.

**My thoughts:** In thinking about this, it might be good to have by volunteer. However, this may end up with a skewed analysis as it is only based on the curation activity and or expert panel that they were originally trained and assigned, respectively. On the flip side, it reduces the responses we receive, and likely those individuals that are volunteering for more than one group would be considered happy!

**Decision:** send it by volunteer.

Thank you for reading my overview of thoughts!

**Comment by yugen** [comment]
@courtneythaxton Next question: can we re-use the 3-month notificaiton and reminder emails for the 6-month? Of course we'd change the relative send dates and references to the surveys.

**Comment by yugen** [comment]
@courtneythaxton You can see three emails sent today in the mail logs (mail-2020-04-16.log) and there should be three sent tomorrow (mail-2020-04-17).  If you copy the links in from the logged emails paste them into the location bar while impersonating a comprehensive user you should go to the survey.

**Comment by courtneythaxton** [comment]
Hi @yugen I looked over the logs for 4-16-20. They look good. Each of the logs had a different due date, so I assume these represent 3 different users that are getting the followup, is that correct?

Since the first email said complete by May 7th, and then the second emails which was a reminder said complete by April 30, and the other one today. So I think that meets the 3 criteria of initial and 2 follow up emails!

For the 4-17-20 log I can see 4 emails to be sent, and these represents Baseline Curation and being assigned to either basic or genetic evidence level. 

these look good!

**Comment by yugen** [comment]
@courtneythaxton I've found the problem that prevented the emails from getting sent last night.  I've updated the test data so that we should have emails tomorrow.
