### ISSUE TITLE
Bug fix: Volunteers with strike through on EP

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/community-curation#21]
@yugen I noticed while looking through the CCDB that there are some volunteers that appear to have their EP they are assigned with a strike through.

Here is the URL for one example: http://community-curation.sirsdemo.unc.edu/volunteers/43
For this individual both their EPs they are assigned to show a strike through.

Here is another example and the individual is only assigned to one group, so I don't think that it is due to the number of assigned groups: http://community-curation.sirsdemo.unc.edu/volunteers/16

I also checked the accepting status of the EP to see if this affected the strikethrough, and it appears to be independent of that.

**Comment by courtneythaxton** [comment]
@yugen. okay I think I got it, these individuals were marked as retired! 

was this an artifact of the import?

**Comment by yugen** [comment]
It appears to be an artifact of the import, but the assignment status incorrect based on the C3 Volunteers sheet.  I'll look into why that is and get back to you.
