### ISSUE TITLE
Add baseline Basic Evidence attestation.

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/community-curation#22]
Users assigned to Baseline CA that have training marked complete should be able to complete an attestation.

- [x] Get attestation questions from courtney
- [x] Build vue component for attestation
- [x] Ensure user taken to attestation form when they click 'sign attestation' button.

**Comment by yugen** [comment]
@courtneythaxton When you have a minute, can you share the the Baseline Volunteer attestation with me?

Thanks!

**Comment by courtneythaxton** [comment]
@yugen here is the version 1 of the attestation. The items may expand as we have a better feel for the process and may update some training. will it be possible to add more questions in the future?

[Baseline Annotation Attestation_v1.docx](https://github.com/clingen-data-model/community-curation/files/4259338/Baseline.Annotation.Attestation_v1.docx)

**Comment by yugen** [comment]
@courtneythaxton  and @lizzkearns,
This is ready for testing.  To test:
1. Go to a baseline volunteer's detail screen 
2. Click the 'Manage Assignments' button.  You should see 'Baseline' in the 'Curation Activities' column in the 'Assignments' table.
3. You should be able to mark training competed (with a date) unless it has already been marked attended.
4. Once training is complete you should be able to click 'Sign attestation' and you should be taken to the Baseline Annotation Attestation.
5. You should only be able to check the 'I, name, attest' checkbox after all other questions have been answered 'Yes'. 
6. Click the 'Complete Attestation' button and you should be redirected back to the volunteer's detail screen.  Clicking 'Manage Assignments' you should see 'assign gene here (coming soon)' under 'Expert Panels' in the Assignments table (note that this text will be updated when gene assignment is completed)

**Comment by courtneythaxton** [comment]
Hi @yugen I have reviewed the Baseline Attestation Process

this workflow worked as expected.

One question, after the Attestation is completed, it does show up in the Attestations Tab for the volunteer. At this time it reads as "Basic Evidence." I wonder if we could update to read "Baseline, Basic evidence" Or "Baseline, Basic" to be consistent with the comprehensive. Especially if we think that individuals may participate in both comprehensive and Baseline, we would want to distinguish those attestations for the volunteer and coordinator.

**Comment by yugen** [comment]
@courtneythaxton The name change you suggest seems right to me.  I've updated baseline aptitudes to "Baseline, Basic Evidence" and "Baseline, Genetic Evidence".
