### ISSUE TITLE
Change the wording of the survey

### ISSUE THREAD

**Issue by lizzkearns** [clingen-data-model/community-curation#25]
On the last page of the survey please Change "You have chosen to become an active member of a curation group. In order to best place your efforts, we ask if you would please prioritize your top three curation activites(s) and expert panel(s) of choice. Further, please indicate any prior experience and willingness to participate in more than one." 
To "You have chosen to become an active member of a curation group. In order to best place your efforts, we ask if you would please choose a curation activity and and expert panel of interest. Further, please indicate any prior experience and willingness to participate in more than one."

**Comment by yugen** [comment]
Changes should be reflected in the survey.
