### ISSUE TITLE
The edit status button is not working

### ISSUE THREAD

**Issue by lizzkearns** [clingen-data-model/community-curation#31]
**To Reproduce**
1. Go to any volunteer (not one that has declined or is unresponsive)
2. Click on Edit Status
3. On my screen it blacks out the rest of the screen and a small blank white box pops up. 
4. It does not give you the option to change status. 

*

**Comment by yugen** [comment]
@lizzkearns This is fixed.  Let me know if you have more trouble. Thanks for the clear description!
