### ISSUE TITLE
As an admin/coordinator I want to select volunteers who need training for a topic and schedule them for an existing training session.

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/community-curation#40]
* Scheduled volunteers should receive and email (content provided by Courtney). Email will come from volunteer@clinicalgenome.org; some language custmized based on training topic, invite message pulled from training session record.

**Comment by yugen** [comment]
* Scheduled volunteers should receive and email (content provided by Courtney). Email should be customized with email address and some language based on training topic.

**Comment by courtneythaxton** [comment]
Update from the C3, per call on 5-12-20: The admins/ coordinators indicated that it would be great if the system can alert them to individuals not trained. This way they can select from this bulk list and have an email sent out for the next training session. 

After selection of the volunteers, they would like the system to send an email of the next training session that they can indicate for a given curation activity and date and time.

I am working on getting the email templates from the current curation activity coordinators, so we can see if one standardized email would be sufficient, or if each activity needs a separate email.

**Comment by yugen** [comment]
@courtneythaxton Can we get on the phone and discuss details of the workflow you describe above?  I'd like to make sure I fully understand before diving in.
