### ISSUE TITLE
As an admin/coordinator I'd like to see the dates volunteers were trained

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/community-curation#46]
* Add 'Training' tab to the volunteer detail scree.  Tab should show date training was marked complete and the assignment for which the training was attended
* Add disclosure with training date to Assignments Card

**Comment by courtneythaxton** [comment]
Hi @yugen I looked at this new tab for training and it looks really nice. 

IT clearly labels the training dates for each activity the volunteer is participating in.

I also tested adding a training to a volunteer (Olivia Rennie- Actionability added), and the information entered in the Manage assignments tab translated to the new trainings tab.
