### ISSUE TITLE
As a coordinator I'd like volunteers to enter they're hypothes.is username in the Baseline evidence attestation.

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/community-curation#52]
Acceptance Criteria:
* hypothes.is username should be required to complete attestation.
* hypothes.is username should be stored on volunteer profile when attestation completed.

**Comment by courtneythaxton** [comment]
@yugen I just tested out the hypothesis.is user ID. I impersonated Mahsa. Upon assigning them a training date, and going into the impersonation mode, I found that on my volunteer user dashboard I nice alert to share my hypothesis user ID, with links to register for one that led me to the hypothesis site. The share with us, took me to a new modal of my demographics where I could update and save info.

**Note: when I tried to save on the share the ID link, the page stayed open and nothing indicated it saved (e.g. the pop up modal disappears).** I did find after I clicked outside of the screen that on the dashboard it updated. IT might be nice after hitting save that the screen disappears.

I was not able to test the attestation directly even when impersonating the volunteer. Once I entered, the dashboard indicates Baseline and trained, but does not show the "sign attestation" for the volunteer. I do see I can sign the attestation as the admin/ coordinator role.

The automated email gives these instructions:  Please login into the 
    <a href=\"https://community-curation.sirsdemo.unc.edu\">ClinGen Community Curation Database</a>, 
    and complete the attestation by selecting the “Sign Attestation” button."

So I assume that means the volunteer should see a sign attestation on their page too?

**Also:** Should the attestation capture the hypothes.is user ID once a volunteer selects "yes" that they have created one? Or does this ID need to be entered afterwards.

**Comment by yugen** [comment]
@courtneythaxton The Baseline attestation now asks for the volunteer's hypothes.is id and adds it to the their record.  It also prepopulates the hypothesis account questions when they've already entered their hypothes.is id.
