### ISSUE TITLE
As a coordinator/ admin I would like the ability to edit Activities and expert panels for a volunteer

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/community-curation#61]
**Is your feature request related to a problem? Please describe.**
At the moment on the Manage assignments tab, as a coordinator I can add expert panels, but I cannot remove. What happened if I had a moment, and entered the wrong EP, how would I change it?

**Describe the solution you'd like**
To enable edit capabilities to update an EP and or date in case of a coordinator user error.

**Describe alternatives you've considered**

**Additional context**

**Comment by yugen** [comment]
@courtneythaxton You can't delete expert-panels and working groups but you can edit them.

I've disabled your ability to delete EPs and WGs b/c they may have other data associated with them and we have not discussed all of the repercussions of deleting one:
- What happens to the assignments to the deleted EP?  Do we notify those volunteers?
- What happens to volunteer priorities that indicate an EP that gets deleted?
- What happens to the EPs associated with a WG when you delete it?

If you'd like the ability to delete expert panels and working groups we'll need to address those questions (and likely more).  If that's how you'd like to proceed please let me know how you'd like to handle the issues raised above.

**Comment by yugen** [comment]
@courtneythaxton I've added a buttons that allow you to "unassign" a volunteer from any assignment.  We don't currently support back-dating assignments (i.e. setting a date that a volunteer is assigned.  Is that something you want to prioritize?

**Comment by courtneythaxton** [comment]
@yugen I think if we at least have the date they were trained in the trainings tab for each volunteer that would be good for now. 

It might be good in the future that it is visible in the "manage assignment" module too.
