### ISSUE TITLE
CCDB Assignments Report does not show all GCEPs

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/community-curation#75]
**Describe the bug**
On the report tab, assignment report selection, when I choose type: comprehensive, activity: gene, the curation group dropdown menu only shows 5 GCEPs. I know that ID/Autism and others should be represented here. 

See image:

**To Reproduce**
1. Go to '...' reports
2. Click on '....' type: comprehensive, activity: gene
3. Scroll down to '....' look at the curation group dropdown menu
4. See error- only 5 GCEPs listed

**Expected behavior**
I would expect a list of all current GCEPS that are accepting, if not all GCEPs that have ever accepted to show as options on the dropdown

**Screenshots**
<img width="1081" alt="Screen Shot 2020-07-31 at 10 35 52 AM" src="https://user-images.githubusercontent.com/32530005/89045721-fe298b00-d319-11ea-8a43-a6afd61b85e1.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS Catalina
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yugen** [comment]
Fixed.
