### ISSUE TITLE
Conversion to Comprehensive in CCDB is not working

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/community-curation#77]
**Describe the bug**
I tried to convert a volunteer from Baseline to comprehensive. When prompted about the convert, and submitting convert, the prompt remained. I did not see the ability of the curator to choose new priorities afterwards.

The volunteer was Michelle Mah.

In the email log I do not see an email sent out, as indicated by the conversion prompt.

**To Reproduce**
1. Go to '...' volunteer, Michelle Mah (or anyone)
2. Click on '....' *** next to volunteer name, and choose "Make Comprehensive"
3. Scroll down to '....' click "convert"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yugen** [comment]
This is fixed.  I have gone ahead and converted Michelle Mah comprehensive.
