### ISSUE TITLE
Receive forbidden error when viewing training session in the CCDB

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/community-curation#91]
![Screen Shot 2020-10-08 at 8 43 19 PM](https://user-images.githubusercontent.com/32530005/95528786-174c5900-09a7-11eb-855a-ab8356ba1e1b.png)
**Describe the bug**
When I go to view the training session for gene curation scheduled for Oct 30, I receive a forbidden error on my browser. I am using google chrome. Also, the current volunteers needing training for gene curation do not populate in this window for me.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yugen** [comment]
Thanks for letting me know about this.  I've fixed the problem. You may be happy to know that the issue only effected users with the 'super-admin' role: that's you and Brooke.
