### ISSUE TITLE
Assignment report in CCDB not working

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/community-curation#96]
**Describe the bug**
The assignment report radio button (blue) on the volunteer tab, as well as the reports tab are not working. When I choose the assignment button on the Volunteer tab, nothing downloads. Also, the current "reports" tab looks identical to the "volunteers" tab. I remember this having a choice of two different reports, assignments and application reports, and I can see neither.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Catalina (version 10.15.5)
 - Browser [e.g. chrome, safari] google Chrome

**Additional context**

**Comment by yugen** [comment]
I've resolved this.  I failed to run a script that updated permissions.  It seems this happens more frequently than it should.  I'll add a ticket to automate these one off scripts that I keep forgetting to run.
