### ISSUE TITLE
Adding new status for volunteers: Oh hold

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/community-curation#97]
**Is your feature request related to a problem? Please describe.**
Some volunteers go through the training and attestation but want to hold being placed for newly developing groups. this essentially means they can get lost to followup. It might be good if we can add a status of "on hold" that we can sort by each month/ quarter to follow up with these volunteers.

**Describe the solution you'd like**
develop a new status of on hold

**Describe alternatives you've considered**
The alternative is to write this in the nots section but then it is not searchable for enhanced followup.

**Additional context**

**Comment by yugen** [comment]
I've added the on-hold volunteer status.  Volunteers with this status will have a blue alert at the top of their detail screen.

**Comment by courtneythaxton** [comment]
great thanks!
