### ISSUE TITLE
CCDB volunteer page sorted to show volunteers that have applied but have not been assigned first

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/community-curation#98]
**Is your feature request related to a problem? Please describe.**
To facilitate the assigning of new volunteers that have recently applied, it would be great if the volunteer tab dashboard of volunteer names was sorted by those that are not assigned first. I"m not sure of the current sorting, although I believe it is alphabetical by last name.

Even when choosing to sort using the status dropdown, the volunteers are still sorted alphabetically. If we could sort by the absence of an assignment, that would be greatly beneficial. 

**Describe alternatives you've considered**
at the moment we can use the reports tab, assignments and sort by trained and find those that have a blank assignment. Then we go through the individual one by one to assign. at least by sorting this way on the dashboard for the volunteer tab, it would reduce one step.

**Additional context**
previously, I thought I had remembered a function to assign newly applied individuals to a curation activity from the dashboard in a demo version, but I am not sure if that is still in effect for the production version. That would also reduce a few steps to the coordinators to assign.

**Comment by yugen** [comment]
Hi @courtneythaxton.  I had added a feature several weeks back that allowed a user to filter volunteers by 'not assigned to curation activity'.  When filtering volunteers that way, the table changes to show their priorities, application date, and a button to assign them.  

I had wondered whether the feature was obvious enough, but based on this issue, i'm guessing it was not.  I've updated the volunteer page to allow the user to select 'Unassigned Volunteers' (default) or 'All Volunteers' to trigger this filtering.  The update is ready for testing at https://ccdb-demo.berglab.unc.edu.  Take a look and let me know what you think.  If you think that works for you, I'll update the training video and push it live.

**Comment by courtneythaxton** [comment]
So I just went back to the  production CCDB, and I see this option now. In my head I had not thought to sort by status of "applied" then activity as "not assigned." I had only performed the first sort. 

I think this makes sense the way you did it, and I can clearly see the assign button. 

Apologies TJ for any confusion, I knew you had this feature, but I had not clearly imprinted in my head which columns got me to this sorting :)

**Comment by yugen** [comment]
No worries.  Like I said, the way the feature was accessed wasn't as obvious as it should have been given the frequency with which it will be used.

I opted for making this feature more obvious because allowing the user to filter by this is much simpler (given that it was already built) than altering the sort logic.

I'll update the training video and push this live this tomorrow.

**Comment by courtneythaxton** [comment]
thanks @yugen sounds good
