### ISSUE TITLE
CCDb volunteer tab vs Activity tab

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/community-curation#99]
**Describe the bug**
I"m n to sure this is a bug, but more like a clarification.

The CCDB has a tab marked "volunteer" and one marked "Activities." At the moment they both display the same things, a list of volunteers, with the option to narrow a search, and the ability to download an assignment report. Is there anything different about the functionality of these two tabs? I just want to make sure I know :)

**Comment by yugen** [comment]
The Activity link in the nav bar takes you to the Activities list screen.  This is a directory that lists all curation activities.  There was a problem with permissions that was redirecting you to the volunteers screen whenever you clicked activities. I've resolved the issue and taken steps to prevent these kinds of permission problems from happening in the future.
